# Copyright 2009 Michael Johnson. All rights reserved.
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file.
application: ghosting-website
version: production
runtime: go
api_version: go1
threadsafe: true

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 150ms
  max_concurrent_requests: 25

handlers:

- url: /_ah/spi/.*
  script: _go_app

- url: /internal/upload-done/.*
  login: admin
  script: _go_app

- url: /internal/process-run
  login: admin
  script: _go_app

- url: /static
  static_dir: public

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public/favicon\.ico

- url: /.*
  static_files: public/index.html
  upload: public/index\.html
